stacks:
  - api
  - frontend

config:
  dev:
    aws_account_id: "111111111111"
    aws_region: us-east-1
  staging:
    aws_account_id: "222222222222"
    aws_region: us-east-1
  prod:
    aws_account_id: "333333333333"
    aws_region: us-west-2
